version: '2'
services:
    gerenciadorprojetos-app:
        image: gerenciadorprojetos
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://gerenciadorprojetos-mysql:3306/gerenciadorprojetos?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    gerenciadorprojetos-mysql:
        extends:
            file: mysql.yml
            service: gerenciadorprojetos-mysql
